/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_tiffannyvarela;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tiffa
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
         at = new adminTiempo(prg_reproducir);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresar = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rdb_usuario = new javax.swing.JRadioButton();
        rdb_artista = new javax.swing.JRadioButton();
        btn_ingresar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_usuario = new javax.swing.JTextField();
        txt_contra = new javax.swing.JTextField();
        date_nacimiento = new com.toedter.calendar.JDateChooser();
        tipodeingreso = new javax.swing.ButtonGroup();
        entrar = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jpass_contra = new javax.swing.JPasswordField();
        btn_entrar = new javax.swing.JButton();
        reproductor = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        prg_reproducir = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_reproducidas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_canciones = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_playlists = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_playlist = new javax.swing.JTable();
        btn_pausaa = new javax.swing.JButton();
        btn_reproducir = new javax.swing.JButton();
        agregarcanciones = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jl_cancionesusuario = new javax.swing.JList<>();
        btn_agregarcancionplaylist = new javax.swing.JButton();
        cmb_cancionesagregar = new javax.swing.JComboBox<>();
        seguirartista = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        cmb_artistas = new javax.swing.JComboBox<>();
        btn_seguirartista = new javax.swing.JButton();
        crearplaylist = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        txt_nombreplaylist = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_generoplaylist = new javax.swing.JTextField();
        date_f_creacionplaylist = new com.toedter.calendar.JDateChooser();
        btn_crear_playlist = new javax.swing.JButton();
        agregaraplaylist = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        cmb_listaplaylist = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cmb_cancionesplaylist = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_cancionesplaylist = new javax.swing.JList<>();
        btn_cancionaplaylist = new javax.swing.JButton();
        btn_terminarplaylist = new javax.swing.JButton();
        verseguidores = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_seguidores = new javax.swing.JList<>();
        nuevoalbum = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_agregarcancionalbum = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_cancionesalbum = new javax.swing.JList<>();
        btn_crearalbum = new javax.swing.JButton();
        txt_nombrealbum = new javax.swing.JTextField();
        txtanioalbum = new javax.swing.JTextField();
        txt_artistaalbum = new javax.swing.JTextField();
        cmb_cancionesalbum = new javax.swing.JComboBox<>();
        nuevacancion = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_nombrecancion = new javax.swing.JTextField();
        txt_anio = new javax.swing.JTextField();
        txt_artistacancion = new javax.swing.JTextField();
        txt_duracioncancion = new javax.swing.JTextField();
        btn_nuevacancion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_ingresar = new javax.swing.JMenu();
        jmi_registro = new javax.swing.JMenuItem();
        jmi_entrar = new javax.swing.JMenuItem();
        jm_usuarios = new javax.swing.JMenu();
        jmi_Agregarcanciones = new javax.swing.JMenuItem();
        jmi_seguirartista = new javax.swing.JMenuItem();
        jmi_crearplaylist = new javax.swing.JMenuItem();
        jmi_agregaraplaylist = new javax.swing.JMenuItem();
        jmi_reproductor = new javax.swing.JMenuItem();
        jm_artista = new javax.swing.JMenu();
        jmi_verseguidores = new javax.swing.JMenuItem();
        jmi_nuevoalbum = new javax.swing.JMenuItem();
        jmi_nuevacancion = new javax.swing.JMenuItem();

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Usuario");

        jLabel7.setText("Contrasena");

        jLabel8.setText("Fecha de nacimiento");

        tipodeingreso.add(rdb_usuario);
        rdb_usuario.setText("Usuario");

        tipodeingreso.add(rdb_artista);
        rdb_artista.setText("Artista");

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ingresarLayout = new javax.swing.GroupLayout(ingresar.getContentPane());
        ingresar.getContentPane().setLayout(ingresarLayout);
        ingresarLayout.setHorizontalGroup(
            ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarLayout.createSequentialGroup()
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ingresarLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ingresarLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(date_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ingresarLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_contra, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                            .addGroup(ingresarLayout.createSequentialGroup()
                                .addComponent(rdb_usuario)
                                .addGap(76, 76, 76)
                                .addComponent(rdb_artista))
                            .addGroup(ingresarLayout.createSequentialGroup()
                                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(31, 31, 31)
                                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                    .addComponent(txt_apellido)
                                    .addComponent(txt_usuario)))))
                    .addGroup(ingresarLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        ingresarLayout.setVerticalGroup(
            ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ingresarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(date_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_usuario)
                    .addComponent(rdb_artista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel2.setText("Usuario");

        jLabel3.setText("Contrasena");

        btn_entrar.setText("Entrar");
        btn_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_entrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout entrarLayout = new javax.swing.GroupLayout(entrar.getContentPane());
        entrar.getContentPane().setLayout(entrarLayout);
        entrarLayout.setHorizontalGroup(
            entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrarLayout.createSequentialGroup()
                .addGroup(entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(entrarLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(entrarLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jpass_contra))
                            .addGroup(entrarLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(entrarLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        entrarLayout.setVerticalGroup(
            entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrarLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpass_contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btn_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        reproductor.setTitle("Reproductor");

        jLabel9.setText("Canciones");

        jLabel10.setText("Playlists");

        tbl_reproducidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Año", "Artista", "Duracion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_reproducidas);

        jl_canciones.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_canciones);

        jl_playlists.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_playlists);

        table_playlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Playlist", "Duracion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(table_playlist);

        btn_pausaa.setText("Pausa");

        btn_reproducir.setText("Reproducir");
        btn_reproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reproducirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reproductorLayout = new javax.swing.GroupLayout(reproductor.getContentPane());
        reproductor.getContentPane().setLayout(reproductorLayout);
        reproductorLayout.setHorizontalGroup(
            reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reproductorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prg_reproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(reproductorLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reproductorLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btn_reproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_pausaa, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        reproductorLayout.setVerticalGroup(
            reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reproductorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(prg_reproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(reproductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pausaa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_reproducir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jLabel26.setText("Canciones");

        jl_cancionesusuario.setModel(new DefaultListModel());
        jScrollPane8.setViewportView(jl_cancionesusuario);

        btn_agregarcancionplaylist.setText("Agregar Cancion");
        btn_agregarcancionplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarcancionplaylistActionPerformed(evt);
            }
        });

        cmb_cancionesagregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        javax.swing.GroupLayout agregarcancionesLayout = new javax.swing.GroupLayout(agregarcanciones.getContentPane());
        agregarcanciones.getContentPane().setLayout(agregarcancionesLayout);
        agregarcancionesLayout.setHorizontalGroup(
            agregarcancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarcancionesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(agregarcancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(agregarcancionesLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(44, 44, 44)
                        .addComponent(cmb_cancionesagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agregarcancionesLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btn_agregarcancionplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        agregarcancionesLayout.setVerticalGroup(
            agregarcancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarcancionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agregarcancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cmb_cancionesagregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_agregarcancionplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel24.setText("Artistas");

        cmb_artistas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        btn_seguirartista.setText("Seguir");

        javax.swing.GroupLayout seguirartistaLayout = new javax.swing.GroupLayout(seguirartista.getContentPane());
        seguirartista.getContentPane().setLayout(seguirartistaLayout);
        seguirartistaLayout.setHorizontalGroup(
            seguirartistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seguirartistaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(seguirartistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmb_artistas, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_seguirartista, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        seguirartistaLayout.setVerticalGroup(
            seguirartistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seguirartistaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(seguirartistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cmb_artistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btn_seguirartista, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jLabel21.setText("Nombre");

        jLabel22.setText("Genero");

        jLabel23.setText("Fecha de creacion");

        btn_crear_playlist.setText("Crear Playlist");
        btn_crear_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crear_playlistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout crearplaylistLayout = new javax.swing.GroupLayout(crearplaylist.getContentPane());
        crearplaylist.getContentPane().setLayout(crearplaylistLayout);
        crearplaylistLayout.setHorizontalGroup(
            crearplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearplaylistLayout.createSequentialGroup()
                .addGroup(crearplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearplaylistLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(crearplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crearplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(crearplaylistLayout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_generoplaylist))
                                .addGroup(crearplaylistLayout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(27, 27, 27)
                                    .addComponent(txt_nombreplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(crearplaylistLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(26, 26, 26)
                                .addComponent(date_f_creacionplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(crearplaylistLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btn_crear_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        crearplaylistLayout.setVerticalGroup(
            crearplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearplaylistLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(crearplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_nombreplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(crearplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txt_generoplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(crearplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(date_f_creacionplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btn_crear_playlist, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel19.setText("Canciones");

        cmb_listaplaylist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cmb_listaplaylist.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_listaplaylistItemStateChanged(evt);
            }
        });

        jLabel20.setText("PlayLists");

        cmb_cancionesplaylist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        jl_cancionesplaylist.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_cancionesplaylist);

        btn_cancionaplaylist.setText("Agregar");
        btn_cancionaplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancionaplaylistActionPerformed(evt);
            }
        });

        btn_terminarplaylist.setText("Terminar");
        btn_terminarplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_terminarplaylistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregaraplaylistLayout = new javax.swing.GroupLayout(agregaraplaylist.getContentPane());
        agregaraplaylist.getContentPane().setLayout(agregaraplaylistLayout);
        agregaraplaylistLayout.setHorizontalGroup(
            agregaraplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregaraplaylistLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(agregaraplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregaraplaylistLayout.createSequentialGroup()
                        .addComponent(btn_cancionaplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btn_terminarplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(agregaraplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(agregaraplaylistLayout.createSequentialGroup()
                            .addComponent(jLabel20)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmb_listaplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(agregaraplaylistLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmb_cancionesplaylist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        agregaraplaylistLayout.setVerticalGroup(
            agregaraplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregaraplaylistLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(agregaraplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_listaplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(30, 30, 30)
                .addGroup(agregaraplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cmb_cancionesplaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(agregaraplaylistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancionaplaylist, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btn_terminarplaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        jl_seguidores.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jl_seguidores);

        javax.swing.GroupLayout verseguidoresLayout = new javax.swing.GroupLayout(verseguidores.getContentPane());
        verseguidores.getContentPane().setLayout(verseguidoresLayout);
        verseguidoresLayout.setHorizontalGroup(
            verseguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verseguidoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        verseguidoresLayout.setVerticalGroup(
            verseguidoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verseguidoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        nuevoalbum.setTitle("Crear Album");

        jLabel15.setText("Nombre Album");

        jLabel16.setText("Año");

        jLabel17.setText("Nombre Artista");

        jLabel18.setText("Canciones");

        txt_agregarcancionalbum.setText("Agregar");
        txt_agregarcancionalbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_agregarcancionalbumActionPerformed(evt);
            }
        });

        jl_cancionesalbum.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(jl_cancionesalbum);

        btn_crearalbum.setText("Crear");
        btn_crearalbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearalbumActionPerformed(evt);
            }
        });

        cmb_cancionesalbum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        javax.swing.GroupLayout nuevoalbumLayout = new javax.swing.GroupLayout(nuevoalbum.getContentPane());
        nuevoalbum.getContentPane().setLayout(nuevoalbumLayout);
        nuevoalbumLayout.setHorizontalGroup(
            nuevoalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoalbumLayout.createSequentialGroup()
                .addGroup(nuevoalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, nuevoalbumLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(nuevoalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nuevoalbumLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(29, 29, 29)
                                .addComponent(txt_nombrealbum))
                            .addGroup(nuevoalbumLayout.createSequentialGroup()
                                .addGroup(nuevoalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nuevoalbumLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(26, 26, 26)
                                        .addComponent(cmb_cancionesalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(nuevoalbumLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtanioalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(nuevoalbumLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_artistaalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 13, Short.MAX_VALUE))))
                    .addGroup(nuevoalbumLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoalbumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(nuevoalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoalbumLayout.createSequentialGroup()
                        .addComponent(btn_crearalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoalbumLayout.createSequentialGroup()
                        .addComponent(txt_agregarcancionalbum)
                        .addGap(148, 148, 148))))
        );
        nuevoalbumLayout.setVerticalGroup(
            nuevoalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoalbumLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(nuevoalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_nombrealbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(nuevoalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtanioalbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(nuevoalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_artistaalbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(nuevoalbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(cmb_cancionesalbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(txt_agregarcancionalbum)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_crearalbum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel11.setText("Nombre");

        jLabel12.setText("Año");

        jLabel13.setText("Artista");

        jLabel14.setText("Duracion");

        btn_nuevacancion.setText("Agregar Cancion");
        btn_nuevacancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevacancionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevacancionLayout = new javax.swing.GroupLayout(nuevacancion.getContentPane());
        nuevacancion.getContentPane().setLayout(nuevacancionLayout);
        nuevacancionLayout.setHorizontalGroup(
            nuevacancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevacancionLayout.createSequentialGroup()
                .addGroup(nuevacancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nuevacancionLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(nuevacancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nuevacancionLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_duracioncancion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nuevacancionLayout.createSequentialGroup()
                                .addGroup(nuevacancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(26, 26, 26)
                                .addGroup(nuevacancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nombrecancion, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(txt_artistacancion)
                                    .addComponent(txt_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(nuevacancionLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btn_nuevacancion, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        nuevacancionLayout.setVerticalGroup(
            nuevacancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevacancionLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(nuevacancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_nombrecancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(nuevacancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(nuevacancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_artistacancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(nuevacancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_duracioncancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btn_nuevacancion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leotify");

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Leotify");

        jm_ingresar.setText("Ingresar");

        jmi_registro.setText("Registro");
        jmi_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_registroActionPerformed(evt);
            }
        });
        jm_ingresar.add(jmi_registro);

        jmi_entrar.setText("Entrar");
        jmi_entrar.setEnabled(false);
        jmi_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_entrarActionPerformed(evt);
            }
        });
        jm_ingresar.add(jmi_entrar);

        jMenuBar1.add(jm_ingresar);

        jm_usuarios.setText("Usuario");

        jmi_Agregarcanciones.setText("Agregar a lista");
        jmi_Agregarcanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_AgregarcancionesActionPerformed(evt);
            }
        });
        jm_usuarios.add(jmi_Agregarcanciones);

        jmi_seguirartista.setText("Seguir Artista");
        jmi_seguirartista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_seguirartistaActionPerformed(evt);
            }
        });
        jm_usuarios.add(jmi_seguirartista);

        jmi_crearplaylist.setText("Crear Playlist");
        jmi_crearplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_crearplaylistActionPerformed(evt);
            }
        });
        jm_usuarios.add(jmi_crearplaylist);

        jmi_agregaraplaylist.setText("Agregar a Playlist");
        jmi_agregaraplaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_agregaraplaylistActionPerformed(evt);
            }
        });
        jm_usuarios.add(jmi_agregaraplaylist);

        jmi_reproductor.setText("Reproductor");
        jmi_reproductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_reproductorActionPerformed(evt);
            }
        });
        jm_usuarios.add(jmi_reproductor);

        jMenuBar1.add(jm_usuarios);

        jm_artista.setText("Artista");

        jmi_verseguidores.setText("Ver Seguidores");
        jmi_verseguidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_verseguidoresActionPerformed(evt);
            }
        });
        jm_artista.add(jmi_verseguidores);

        jmi_nuevoalbum.setText("Album Nuevo");
        jmi_nuevoalbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_nuevoalbumActionPerformed(evt);
            }
        });
        jm_artista.add(jmi_nuevoalbum);

        jmi_nuevacancion.setText("Cancion Nueva");
        jmi_nuevacancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_nuevacancionActionPerformed(evt);
            }
        });
        jm_artista.add(jmi_nuevacancion);

        jMenuBar1.add(jm_artista);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(548, 548, 548)
                .addComponent(jLabel1)
                .addContainerGap(614, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(563, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_entrarActionPerformed
        // TODO add your handling code here:
        entrar.setModal(true);
        entrar.pack();
        entrar.setLocationRelativeTo(this);
        entrar.setVisible(true);
    }//GEN-LAST:event_jmi_entrarActionPerformed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // TODO add your handling code here:
        String nombre, apellido, usuario, contra;
        Date f_nacimiento;

        try {
            nombre = txt_nombre.getText();
            apellido = txt_apellido.getText();
            usuario = txt_usuario.getText();
            contra = txt_contra.getText();
            f_nacimiento = date_nacimiento.getDate();

            if (rdb_artista.isSelected()) {
                persona a = new artista(nombre, apellido, usuario, contra, f_nacimiento);
                personas.add(a);
                adminArtista aa = new adminArtista("./Binarios/artistas.tavb");
                aa.cargarArchivo();
                aa.setArtistas(personas);
                aa.escribirArchivo();
                DefaultComboBoxModel modelo1 = (DefaultComboBoxModel) cmb_artistas.getModel();
                modelo1.addElement(a);
                cmb_artistas.setModel(modelo1);
            }

            if (rdb_usuario.isSelected()) {
                persona u = new usuario(nombre, apellido, usuario, contra, f_nacimiento);
                personas.add(u);
                adminUsuario au = new adminUsuario("./Binarios/usuarios.tavb");
                au.cargarArchivo();
                au.setUsuarios(personas);
                au.escribirArchivo();

            }
            JOptionPane.showMessageDialog(ingresar, "Persona agregada correctamente");
            jmi_entrar.setEnabled(true);
            txt_apellido.setText("");
            txt_contra.setText("");
            txt_nombre.setText("");
            txt_usuario.setText("");
            date_nacimiento.setDate(new Date());
        } catch (Exception e) {

            e.printStackTrace();
            JOptionPane.showMessageDialog(ingresar, "Error");
        }


    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void jmi_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_registroActionPerformed
        // TODO add your handling code here:
        ingresar.setModal(true);
        ingresar.pack();
        ingresar.setLocationRelativeTo(this);
        ingresar.setVisible(true);
    }//GEN-LAST:event_jmi_registroActionPerformed

    private void btn_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entrarActionPerformed
        // TODO add your handling code here:
        
        try {
            for (int i = 0; i < personas.size(); i++) {
            if (txt_user.getText().equals(((usuario)personas.get(i)).getUsuario())&&jpass_contra.getText().equals(((usuario)personas.get(i)).getContra())) {
                JOptionPane.showMessageDialog(entrar, "Bienvenido");
                jm_usuarios.setEnabled(true);
                entrar.setVisible(false); 
            }
            
            if (txt_user.getText().equals(((artista)personas.get(i)).getUsuario())&&jpass_contra.getText().equals(((artista)personas.get(i)).getContra())) {
                JOptionPane.showMessageDialog(entrar, "Bienvenido");
                jm_artista.setEnabled(true);
                entrar.setVisible(false);
            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(entrar, "Usuario y contrasena no validos");
        }
        finally{
            txt_user.setText("");
            jpass_contra.setText("");
            
        }
    }//GEN-LAST:event_btn_entrarActionPerformed

    private void btn_nuevacancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevacancionActionPerformed
        // TODO add your handling code here:
        String nombre, artista;
        int anio, duracion;
        
        try {
            nombre=txt_nombrecancion.getText();
        artista=txt_artistacancion.getText();
        
        anio=Integer.parseInt(txt_anio.getText());
        duracion=Integer.parseInt(txt_duracioncancion.getText());
        
        cancion c = new cancion(nombre, anio, artista, duracion);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_cancionesagregar.getModel();
        modelo.addElement(c);
        cmb_cancionesagregar.setModel(modelo);
        cmb_cancionesalbum.setModel(modelo);
        cmb_cancionesplaylist.setModel(modelo);
        JOptionPane.showMessageDialog(nuevacancion, "Agregada");
        txt_nombrecancion.setText("");
        txt_artistacancion.setText("");
        txt_anio.setText("");
        txt_duracioncancion.setText("");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(ingresar, "Error");
        }
    }//GEN-LAST:event_btn_nuevacancionActionPerformed

    private void btn_crearalbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearalbumActionPerformed
        // TODO add your handling code here:
        String nombre,artista;
        int anio;
        
        try {
            nombre=txt_nombrealbum.getText();
        artista=txt_artistaalbum.getText();
        
        anio=Integer.parseInt(txtanioalbum.getText());
        JOptionPane.showMessageDialog(nuevoalbum, "Creado");
        txt_nombrealbum.setText("");
        txt_artistaalbum.setText("");
        txtanioalbum.setText("");
        DefaultListModel modelo = (DefaultListModel) jl_cancionesalbum.getModel();
        modelo.clear();
        cmb_cancionesalbum.setSelectedIndex(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(nuevoalbum, "Error");
        }
        
        
    }//GEN-LAST:event_btn_crearalbumActionPerformed

    private void txt_agregarcancionalbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_agregarcancionalbumActionPerformed
        // TODO add your handling code here:
        album al = new album();
        DefaultListModel modelo = (DefaultListModel) jl_cancionesalbum.getModel();
        modelo.addElement((cancion)cmb_cancionesalbum.getSelectedItem());
        al.addCanciones((cancion)cmb_cancionesalbum.getSelectedItem());
        jl_cancionesalbum.setModel(modelo);
    }//GEN-LAST:event_txt_agregarcancionalbumActionPerformed

    private void jmi_AgregarcancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_AgregarcancionesActionPerformed
        // TODO add your handling code here:
        agregarcanciones.setModal(true);
        agregarcanciones.pack();
        agregarcanciones.setLocationRelativeTo(this);
        agregarcanciones.setVisible(true);
    }//GEN-LAST:event_jmi_AgregarcancionesActionPerformed

    private void jmi_seguirartistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_seguirartistaActionPerformed
        // TODO add your handling code here:
        seguirartista.setModal(true);
        seguirartista.pack();
        seguirartista.setLocationRelativeTo(this);
        seguirartista.setVisible(true);
    }//GEN-LAST:event_jmi_seguirartistaActionPerformed

    private void jmi_crearplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_crearplaylistActionPerformed
        // TODO add your handling code here:
        crearplaylist.setModal(true);
        crearplaylist.pack();
        crearplaylist.setLocationRelativeTo(this);
        crearplaylist.setVisible(true);
    }//GEN-LAST:event_jmi_crearplaylistActionPerformed

    private void jmi_agregaraplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_agregaraplaylistActionPerformed
        // TODO add your handling code here:
        agregaraplaylist.setModal(true);
        agregaraplaylist.pack();
        agregaraplaylist.setLocationRelativeTo(this);
        agregaraplaylist.setVisible(true);
    }//GEN-LAST:event_jmi_agregaraplaylistActionPerformed

    private void jmi_reproductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_reproductorActionPerformed
        // TODO add your handling code here:
        reproductor.setModal(true);
        reproductor.pack();
        reproductor.setLocationRelativeTo(this);
        reproductor.setVisible(true);
    }//GEN-LAST:event_jmi_reproductorActionPerformed

    private void jmi_verseguidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_verseguidoresActionPerformed
        // TODO add your handling code here:
        verseguidores.setModal(true);
        verseguidores.pack();
        verseguidores.setLocationRelativeTo(this);
        verseguidores.setVisible(true);
    }//GEN-LAST:event_jmi_verseguidoresActionPerformed

    private void jmi_nuevoalbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_nuevoalbumActionPerformed
        // TODO add your handling code here:
        nuevoalbum.setModal(true);
        nuevoalbum.pack();
        nuevoalbum.setLocationRelativeTo(this);
        nuevoalbum.setVisible(true);
    }//GEN-LAST:event_jmi_nuevoalbumActionPerformed

    private void jmi_nuevacancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_nuevacancionActionPerformed
        // TODO add your handling code here:
        nuevacancion.setModal(true);
        nuevacancion.pack();
        nuevacancion.setLocationRelativeTo(this);
        nuevacancion.setVisible(true);
    }//GEN-LAST:event_jmi_nuevacancionActionPerformed

    private void btn_crear_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crear_playlistActionPerformed
        // TODO add your handling code here:
        String nombre,genero;
        Date f_creacion;
        int duracion=0;
        
        try {
            nombre = txt_nombreplaylist.getText();
            genero = txt_generoplaylist.getText();
            f_creacion = date_f_creacionplaylist.getDate();
            playlist pl = new playlist(nombre, genero, f_creacion, duracion);
            JOptionPane.showMessageDialog(crearplaylist, "Playlist Creada");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cmb_listaplaylist.getModel();
            modelo.addElement(pl);
            cmb_listaplaylist.setModel(modelo);
           
            txt_nombreplaylist.setText("");
            txt_generoplaylist.setText("");
            date_f_creacionplaylist.setDate(new Date());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(crearplaylist, "Error");
        }

    }//GEN-LAST:event_btn_crear_playlistActionPerformed

    private void btn_cancionaplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancionaplaylistActionPerformed
        // TODO add your handling code here:
        
        playlist pl = new playlist();
        DefaultListModel modelo = (DefaultListModel) jl_cancionesplaylist.getModel();
        modelo.addElement((cancion)cmb_cancionesplaylist.getSelectedItem());
        pl.addCanciones((cancion)cmb_cancionesplaylist.getSelectedItem());
        duracion+=((cancion)cmb_cancionesplaylist.getSelectedItem()).getDuracion();
        jl_cancionesplaylist.setModel(modelo);
        
    }//GEN-LAST:event_btn_cancionaplaylistActionPerformed

    private void cmb_listaplaylistItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_listaplaylistItemStateChanged
        // TODO add your handling code here:
        DefaultListModel modelo = (DefaultListModel) jl_cancionesplaylist.getModel();
        if (evt.getStateChange() ==1 ) {
            playlist pl = (playlist) cmb_listaplaylist.getSelectedItem();
            
            for (int i = 0; i < pl.getCanciones().size(); i++) {
                modelo.add(i, pl.getCanciones().get(i));
            }
            jl_cancionesplaylist.setModel(modelo);
        }
    }//GEN-LAST:event_cmb_listaplaylistItemStateChanged

    private void btn_terminarplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_terminarplaylistActionPerformed
        // TODO add your handling code here:
        try {
            DefaultListModel modelo = (DefaultListModel) jl_cancionesplaylist.getModel();
        playlist pl =new playlist();
        pl.setDuracion(duracion);
        JOptionPane.showMessageDialog(agregaraplaylist, "Agregados");
        cmb_listaplaylist.setSelectedIndex(0);
        cmb_cancionesplaylist.setSelectedIndex(0);
        modelo.clear();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(agregaraplaylist, "Error");
        }
        
    }//GEN-LAST:event_btn_terminarplaylistActionPerformed

    private void btn_agregarcancionplaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarcancionplaylistActionPerformed
        // TODO add your handling code here:
        usuario u = new usuario();
        try {
            u.addCanciones((cancion)cmb_cancionesagregar.getSelectedItem());
            DefaultListModel modelo = (DefaultListModel) jl_cancionesusuario.getModel();
            modelo.addElement((cancion)cmb_cancionesagregar.getSelectedItem());
            jl_canciones.setModel(modelo);
            jl_cancionesusuario.setModel(modelo);
            JOptionPane.showMessageDialog(agregarcanciones, "Cancion agregada");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(agregarcanciones, "Error");
        }
    }//GEN-LAST:event_btn_agregarcancionplaylistActionPerformed

    private void btn_reproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reproducirActionPerformed
        // TODO add your handling code here:
        int pos = jl_canciones.getSelectedIndex();
        DefaultListModel modelo = (DefaultListModel) jl_canciones.getModel();
        Object [] newrow= {
            ((cancion)modelo.get(pos)).getNombre_cancion(),
            ((cancion)modelo.get(pos)).getAnio(),
            ((cancion)modelo.get(pos)).getNombre_artista(),
            ((cancion)modelo.get(pos)).getDuracion()
        };
        DefaultTableModel modelo1 = (DefaultTableModel) tbl_reproducidas.getModel();
                modelo1.addRow(newrow);
                tbl_reproducidas.setModel(modelo1);
                cancion c = (cancion) modelo.getElementAt(pos);
    }//GEN-LAST:event_btn_reproducirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog agregaraplaylist;
    private javax.swing.JDialog agregarcanciones;
    private javax.swing.JButton btn_agregarcancionplaylist;
    private javax.swing.JButton btn_cancionaplaylist;
    private javax.swing.JButton btn_crear_playlist;
    private javax.swing.JButton btn_crearalbum;
    private javax.swing.JButton btn_entrar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_nuevacancion;
    private javax.swing.JButton btn_pausaa;
    private javax.swing.JButton btn_reproducir;
    private javax.swing.JButton btn_seguirartista;
    private javax.swing.JButton btn_terminarplaylist;
    private javax.swing.JComboBox<String> cmb_artistas;
    private javax.swing.JComboBox<String> cmb_cancionesagregar;
    private javax.swing.JComboBox<String> cmb_cancionesalbum;
    private javax.swing.JComboBox<String> cmb_cancionesplaylist;
    private javax.swing.JComboBox<String> cmb_listaplaylist;
    private javax.swing.JDialog crearplaylist;
    private com.toedter.calendar.JDateChooser date_f_creacionplaylist;
    private com.toedter.calendar.JDateChooser date_nacimiento;
    private javax.swing.JDialog entrar;
    private javax.swing.JDialog ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JList<String> jl_canciones;
    private javax.swing.JList<String> jl_cancionesalbum;
    private javax.swing.JList<String> jl_cancionesplaylist;
    private javax.swing.JList<String> jl_cancionesusuario;
    private javax.swing.JList<String> jl_playlists;
    private javax.swing.JList<String> jl_seguidores;
    private javax.swing.JMenu jm_artista;
    private javax.swing.JMenu jm_ingresar;
    private javax.swing.JMenu jm_usuarios;
    private javax.swing.JMenuItem jmi_Agregarcanciones;
    private javax.swing.JMenuItem jmi_agregaraplaylist;
    private javax.swing.JMenuItem jmi_crearplaylist;
    private javax.swing.JMenuItem jmi_entrar;
    private javax.swing.JMenuItem jmi_nuevacancion;
    private javax.swing.JMenuItem jmi_nuevoalbum;
    private javax.swing.JMenuItem jmi_registro;
    private javax.swing.JMenuItem jmi_reproductor;
    private javax.swing.JMenuItem jmi_seguirartista;
    private javax.swing.JMenuItem jmi_verseguidores;
    private javax.swing.JPasswordField jpass_contra;
    private javax.swing.JDialog nuevacancion;
    private javax.swing.JDialog nuevoalbum;
    private javax.swing.JProgressBar prg_reproducir;
    private javax.swing.JRadioButton rdb_artista;
    private javax.swing.JRadioButton rdb_usuario;
    private javax.swing.JDialog reproductor;
    private javax.swing.JDialog seguirartista;
    private javax.swing.JTable table_playlist;
    private javax.swing.JTable tbl_reproducidas;
    private javax.swing.ButtonGroup tipodeingreso;
    private javax.swing.JButton txt_agregarcancionalbum;
    private javax.swing.JTextField txt_anio;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_artistaalbum;
    private javax.swing.JTextField txt_artistacancion;
    private javax.swing.JTextField txt_contra;
    private javax.swing.JTextField txt_duracioncancion;
    private javax.swing.JTextField txt_generoplaylist;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombrealbum;
    private javax.swing.JTextField txt_nombrecancion;
    private javax.swing.JTextField txt_nombreplaylist;
    private javax.swing.JTextField txt_user;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JTextField txtanioalbum;
    private javax.swing.JDialog verseguidores;
    // End of variables declaration//GEN-END:variables

    ArrayList<persona> personas = new ArrayList();
    ArrayList <cancion> canciones = new ArrayList();
    int duracion=0;
    adminTiempo at;
}   
